/**
 * Data update metadata
 *
 * This file is auto-generated by the merge scripts to track when
 * different data sources were last updated. It provides fallback
 * values for Vite dev mode (which doesn't have access to Deno KV).
 *
 * Do not edit manually - run the merge scripts to update these values.
 */

/** Date of the most recent DARKO CSV file (YYYY-MM-DD format) */
export const DARKO_UPDATED = "2026-02-05";

/** Date when player stats were last synced from NBA API (YYYY-MM-DD format) */
export const PLAYER_STATS_UPDATED = "2026-02-05";

/** Date when the salary model data was last updated (YYYY-MM-DD format) */
export const SALARY_MODEL_UPDATED = "2026-01-21";
