/**
 * Merge NBA stats into the Deno KV database
 *
 * This script reads the NBA stats JSON file (created by fetch_nba_stats.py)
 * and merges the avgMinutes and gamesPlayed data into existing player records
 * in the KV database.
 *
 * The actual matching/merging logic lives in lib/merge-stats-core.ts so it
 * can also be used by the automated cron job. This script handles file I/O,
 * KV access, fallback file updates, and console reporting.
 *
 * Usage: deno task merge-stats
 */

import { getPlayers, setPlayers } from "../lib/players-data.ts";
import { mergeNbaStats } from "../lib/merge-stats-core.ts";
import type { NbaStats } from "../lib/merge-stats-core.ts";
import type { Player } from "../lib/types.ts";

/**
 * Update the fallback players.ts file with merged data
 *
 * This is necessary because Vite dev mode doesn't have access to Deno KV,
 * so we need to update the hardcoded fallback data to include avgMinutes.
 */
async function updateFallbackFile(players: Player[]) {
  const fallbackPath = new URL("../lib/players.ts", import.meta.url);

  // Generate the new file content
  const playerLines = players.map((p) => {
    const futureSalaries = JSON.stringify(p.futureSalaries);
    // Include avgMinutes, gamesPlayed, recentGamesPlayed, and projectedGames if they exist
    const extras: string[] = [];
    if (p.avgMinutes !== undefined) {
      extras.push(`avgMinutes: ${p.avgMinutes}`);
    }
    if (p.gamesPlayed !== undefined) {
      extras.push(`gamesPlayed: ${p.gamesPlayed}`);
    }
    if (p.recentGamesPlayed !== undefined) {
      extras.push(`recentGamesPlayed: ${p.recentGamesPlayed}`);
    }
    if (p.projectedGames !== undefined) {
      extras.push(`projectedGames: ${p.projectedGames}`);
    }
    const extrasStr = extras.length > 0 ? `, ${extras.join(", ")}` : "";
    return `{ name: "${p.name}", team: "${p.team}", age: ${p.age}, darko: ${p.darko}, actualSalary: ${p.actualSalary}, futureSalaries: ${futureSalaries}${extrasStr} }`;
  });

  const fileContent = `/**
 * Fallback player data for the NBA Salary Model
 *
 * This hardcoded data is used when Deno KV is empty or unavailable.
 * In normal operation, the app fetches data from KV instead.
 */
import type { Player } from "./types.ts";

export type { Player };

export const PLAYER_DATA: Player[] = [
${playerLines.join(",\n")}
];
`;

  await Deno.writeTextFile(fallbackPath, fileContent);
  console.log("   Updated lib/players.ts fallback file");
}

/**
 * Update the metadata.ts file with the new player stats date
 *
 * This file provides fallback metadata for Vite dev mode.
 */
async function updateMetadataFile(playerStatsDate: string) {
  const metadataPath = new URL("../lib/metadata.ts", import.meta.url);

  // Read current file to preserve other values
  const currentContent = await Deno.readTextFile(metadataPath);

  // Extract current values using regex
  const darkoMatch = currentContent.match(/DARKO_UPDATED = "([^"]+)"/);
  const salaryModelMatch = currentContent.match(
    /SALARY_MODEL_UPDATED = "([^"]+)"/,
  );

  const darkoDate = darkoMatch?.[1] ?? "2026-01-21";
  const salaryModelDate = salaryModelMatch?.[1] ?? "2026-01-21";

  const fileContent = `/**
 * Data update metadata
 *
 * This file is auto-generated by the merge scripts to track when
 * different data sources were last updated. It provides fallback
 * values for Vite dev mode (which doesn't have access to Deno KV).
 *
 * Do not edit manually - run the merge scripts to update these values.
 */

/** Date of the most recent DARKO CSV file (YYYY-MM-DD format) */
export const DARKO_UPDATED = "${darkoDate}";

/** Date when player stats were last synced from NBA API (YYYY-MM-DD format) */
export const PLAYER_STATS_UPDATED = "${playerStatsDate}";

/** Date when the salary model data was last updated */
export const SALARY_MODEL_UPDATED = "${salaryModelDate}";
`;

  await Deno.writeTextFile(metadataPath, fileContent);
  console.log("   Updated lib/metadata.ts");
}

/**
 * Main function to merge stats
 */
async function main() {
  console.log("Merging NBA stats into KV database...");

  // Read the stats JSON file created by the Python script
  const statsPath = new URL("./nba_stats.json", import.meta.url);
  let nbaStats: NbaStats;

  try {
    const statsText = await Deno.readTextFile(statsPath);
    nbaStats = JSON.parse(statsText);
    console.log(
      `   Loaded ${Object.keys(nbaStats).length} players from NBA API`,
    );
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      console.error("nba_stats.json not found!");
      console.log("   Run 'python scripts/fetch_nba_stats.py' first");
      Deno.exit(1);
    }
    throw error;
  }

  // Get current players from KV
  const { players } = await getPlayers();
  console.log(`   Found ${players.length} players in KV database`);

  // Use the shared merge function to match and merge stats
  const result = mergeNbaStats(players, nbaStats);

  // Save updated players back to KV
  // Record today's date as when player stats were updated
  const today = new Date().toISOString().split("T")[0]; // YYYY-MM-DD format
  await setPlayers(result.updatedPlayers, { playerStatsUpdated: today });

  // Also update the fallback file (lib/players.ts) for Vite dev mode
  // Since Vite doesn't have access to Deno KV, we need the fallback to have the data too
  await updateFallbackFile(result.updatedPlayers);
  await updateMetadataFile(today);

  // Report results
  console.log("");
  console.log(`Merge complete!`);
  console.log(`   Matched: ${result.matchedCount} players`);
  console.log(`   Unmatched: ${result.unmatchedPlayers.length} players`);

  // Report team changes (trades, signings, etc.)
  if (result.teamChanges.length > 0) {
    console.log("");
    console.log(`Team changes detected: ${result.teamChanges.length}`);
    for (const change of result.teamChanges) {
      console.log(`   ${change.name}: ${change.oldTeam} -> ${change.newTeam}`);
    }
  }

  if (
    result.unmatchedPlayers.length > 0 && result.unmatchedPlayers.length <= 20
  ) {
    console.log("");
    console.log("   Unmatched players:");
    for (const name of result.unmatchedPlayers) {
      console.log(`     - ${name}`);
    }
  } else if (result.unmatchedPlayers.length > 20) {
    console.log("");
    console.log(`   First 20 unmatched players:`);
    for (const name of result.unmatchedPlayers.slice(0, 20)) {
      console.log(`     - ${name}`);
    }
    console.log(`     ... and ${result.unmatchedPlayers.length - 20} more`);
  }

  console.log("");
  console.log("   Run 'deno task check-kv' to verify the data");
}

main().catch((error) => {
  console.error("Error:", error);
  Deno.exit(1);
});
